{
 "title": "Food-Energy System Health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (handler) (\r\n  rate(http_requests_total[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4xx|5xx\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(http_request_duration_seconds_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "up{job=\"food-energy-backend\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}