apiVersion: v1
kind: Service
metadata:
  name: food-energy-backend
  namespace: food-energy
spec:
  selector:
    app: food-energy-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP