"""
notebook.py
------------
A Notebook is the primary artifact a researcher exports, shares, and
cites: an ordered sequence of entries, each referencing one or more real
Experiments plus the researcher's own annotation/conclusion. This module
resolves a stored notebook into a full view (embedding each referenced
experiment's summary + health) and generates a self-contained Markdown
export with a reproducibility appendix.
"""
from __future__ import annotations

from datetime import datetime

from . import notebook_store as store
from . import experiment_store as exp_store
from .health import compute_health, model_fingerprint


def create_notebook(title: str, description: str | None = None, author: str | None = None) -> dict:
    return store.create_notebook(title, description, author)


def list_notebooks() -> list[dict]:
    return store.list_notebooks()


def add_entry(notebook_id: str, entry_type: str, experiment_ids: list[str], text: str | None) -> dict | None:
    return store.add_entry(notebook_id, entry_type, experiment_ids, text)


def update_entry(entry_id: str, text: str) -> dict | None:
    return store.update_entry_text(entry_id, text)


def delete_entry(entry_id: str) -> bool:
    return store.delete_entry(entry_id)


def delete_notebook(notebook_id: str) -> bool:
    return store.delete_notebook(notebook_id)


def _resolve_experiment_summary(experiment_id: str) -> dict | None:
    exp = exp_store.load_experiment(experiment_id)
    if exp is None:
        return None
    r = exp["result"]
    return {
        "id": exp["metadata"]["id"],
        "label": exp["metadata"]["label"],
        "mode": exp["metadata"]["mode"],
        "created_at": exp["metadata"]["created_at"],
        "spec": exp["spec"],
        "anchor_year": r["anchor_year"],
        "target_year": r["target_year"],
        "summary": r["summary"],
        "baseline_summary": r["baseline_summary"],
        "cascade_total_affected": r["cascade"]["total_affected"] if r.get("cascade") else 0,
        "uncertainty": r.get("uncertainty"),
        "explanation": r.get("explanation"),
        "health": compute_health(exp),
    }


def get_notebook(notebook_id: str) -> dict | None:
    meta = store.get_notebook_meta(notebook_id)
    if meta is None:
        return None
    entries_raw = store.list_entries(notebook_id)
    entries = []
    for e in entries_raw:
        experiments = [s for eid in e["experiment_ids"] if (s := _resolve_experiment_summary(eid)) is not None]
        entries.append({
            "id": e["id"], "entry_type": e["entry_type"], "text": e["text"],
            "created_at": e["created_at"], "experiments": experiments,
        })
    return {"metadata": meta, "entries": entries}


def export_markdown(notebook_id: str) -> str | None:
    nb = get_notebook(notebook_id)
    if nb is None:
        return None
    m = nb["metadata"]
    lines = [
        f"# {m['title']}",
        "",
        f"*{m.get('description') or ''}*" if m.get("description") else "",
        "",
        f"**Author:** {m.get('author') or 'unattributed'}  ",
        f"**Created:** {m['created_at']}  ",
        f"**Last updated:** {m['updated_at']}  ",
        f"**Model version (fingerprint):** `{model_fingerprint()}`  ",
        "",
        "Generated by the Systemic Risk Observatory Experiment Studio. Every "
        "figure below was computed by the real agent-based model, not "
        "estimated -- see the Reproducibility appendix to rerun any entry "
        "exactly.",
        "",
        "---",
        "",
    ]

    for i, entry in enumerate(nb["entries"], 1):
        lines.append(f"## {i}. {entry['entry_type'].replace('_', ' ').title()}")
        lines.append("")
        if entry["text"]:
            lines.append(entry["text"])
            lines.append("")
        for exp in entry["experiments"]:
            h = exp["health"]
            lines.append(f"**Experiment: {exp['label']}** (`{exp['id']}`, mode: {exp['mode']})")
            lines.append("")
            lines.append(f"- Window: {exp['anchor_year']} \u2192 {exp['target_year']}")
            lines.append(f"- Peak price index: {exp['summary'].get('max_price_index')} "
                          f"(baseline: {exp['baseline_summary'].get('max_price_index')})")
            lines.append(f"- Peak population at risk: {exp['summary'].get('max_PAR_millions')}M "
                          f"(baseline: {exp['baseline_summary'].get('max_PAR_millions')}M)")
            lines.append(f"- Nodes genuinely affected (shock-isolated): {exp['cascade_total_affected']}")
            if exp["uncertainty"]:
                lines.append(f"- Uncertainty: Monte Carlo ensemble reported (see appendix for full stats)")
            lines.append(f"- **Validation status:** {h['validation']['detail']}")
            lines.append(f"- **Uncertainty status:** {h['uncertainty']['note']}")
            if exp["explanation"]:
                lines.append("")
                lines.append(f"> {exp['explanation']}")
            lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("## Reproducibility appendix")
    lines.append("")
    lines.append("Exact specifications to rerun any experiment referenced above:")
    lines.append("")
    seen = set()
    for entry in nb["entries"]:
        for exp in entry["experiments"]:
            if exp["id"] in seen:
                continue
            seen.add(exp["id"])
            lines.append(f"### `{exp['id']}` \u2014 {exp['label']}")
            lines.append("```json")
            import json as _json
            lines.append(_json.dumps(exp["spec"], indent=2))
            lines.append("```")
            lines.append("")
            lines.append("**Known limitations of this model configuration:**")
            for lim in exp["health"]["limitations"][:3]:
                lines.append(f"- {lim}")
            lines.append("")

    lines.append(f"*Exported {datetime.utcnow().isoformat()}Z*")
    return "\n".join(lines)


def export_json(notebook_id: str) -> dict | None:
    return get_notebook(notebook_id)
